# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14v'

- script: |
    npm install
  displayName: 'Install App Files'
- task: Npm@1
  displayName: 'Publish Package to Feed weightTracker'
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: 'ae8615ac-02b0-435b-9754-21090cf9744f'