# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14v'

- script: |
    npm install
  displayName: 'Install App Files'

- task: Npm@1
  inputs:
    command: 'publish'
    verbose: true
    publishRegistry: 'useFeed'
    publishFeed: '227f0bf8-12b7-4009-a24e-64b4f3457d20/9385fe3e-08c1-48a1-a8d9-375e55a03617'